# Generated by Django 2.2.5 on 2019-09-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_tag_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
    ]
